## avm

### device

GET {{baseUrl}}/homeautoswitch/devicelist/11630%200481724

### devicelist

GET {{baseUrl}}/homeautoswitch/devicelist/

## device

### create device

POST {{baseUrl}}/devices
content-type: application/json

{
  "name": "omv-heavy",
  "ain": "11630%200481724"
}

### get devices

GET {{baseUrl}}/devices

### store dataset

POST {{baseUrl}}/devices/1/data-sets

### get dataset

GET {{baseUrl}}/devices/1/data-sets
