name: 'Build App'

on:
  workflow_call:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data-ui
          path: power-data-
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data-ui
          path: power-data-ui
      - run: docker build -t power-data -f power-data/Dockerfile .
      - run: docker save power-data > /tmp/power-data.tar
      - uses: actions/upload-artifact@v4
        with:
          name: power-data
          path: /tmp/power-data.tar